name = "FPIL"
version = "0.1.0"
defaultTargets = ["fpil"]

[[lean_lib]]
name = "FPIL"

[[lean_exe]]
name = "fpil"
root = "Main"

[[require]]
name = "Cli"
git = "https://github.com/leanprover/lean4-cli"
rev = "main"
